version: '3.10-slim'
services:
  # client:
  #   build:
  #     context: ./client
  #   ports:
  #     - "3000:3000"
  #   restart: always
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    restart: always

